service: yyt-config-api
provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: ap-northeast-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:HeadObject'
        - 's3:GetObject'
        - 's3:PutObject'
        - 's3:PutObjectAcl'
        - 's3:DeleteObject'
      Resource:
        - 'arn:aws:s3:::${env:CONFIG_BUCKET}/*'
  environment:
    CONFIG_BUCKET: ${env:CONFIG_BUCKET}
    CONFIG_SECRET: ${env:CONFIG_SECRET}

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  authorizeToken:
    handler: src/index.authorizeToken
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: /auth/{systemKey}
          method: put
          request:
            parameters:
              paths:
                systemKey: true
  deleteToken:
    handler: src/index.deleteToken
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: /auth/{systemKey}
          method: delete
          request:
            parameters:
              paths:
                systemKey: true
  listAuthorizedTokens:
    handler: src/index.listAuthorizedTokens
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: /auth/{systemKey}
          method: get
          request:
            parameters:
              paths:
                systemKey: true
  validateToken:
    handler: src/index.validateToken
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: /auth/{systemKey}
          method: post
          request:
            parameters:
              paths:
                systemKey: true

resources:
  Resources:
    ConfigBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:CONFIG_BUCKET}
